### ISSUE TITLE
FactoryConfigurationError : 

### ISSUE THREAD

**Issue by aqibmapari** [alipov/ews-android-api#5] opened 2016-04-06 10:14 UTC
Code compiles well but when I try calling the mail send() method I get the below error.
I am using Eclipse IDE.

> `04-06 15:27:30.664: E/AndroidRuntime(13175): Process: com.intellect.bsalesapp, PID: 13175
> 04-06 15:27:30.664: E/AndroidRuntime(13175): android.javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.XMLOutputFactoryBase not found
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at android.javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at android.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:176)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at android.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at android.javax.xml.stream.XMLOutputFactory.newInstance(XMLOutputFactory.java:98)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at microsoft.exchange.webservices.data.core.EwsServiceXmlWriter.<init>(EwsServiceXmlWriter.java:101)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:690)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:665)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:635)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at microsoft.exchange.webservices.data.core.ExchangeService.internalCreateItems(ExchangeService.java:598)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at microsoft.exchange.webservices.data.core.ExchangeService.createItem(ExchangeService.java:657)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at microsoft.exchange.webservices.data.core.service.item.Item.internalCreate(Item.java:245)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at microsoft.exchange.webservices.data.core.service.item.EmailMessage.internalSend(EmailMessage.java:147)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at microsoft.exchange.webservices.data.core.service.item.EmailMessage.send(EmailMessage.java:258)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at com.phonegap.plugins.Mail.send(Mail.java:98)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at com.phonegap.plugins.SendMail$2.run(SendMail.java:79)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> 04-06 15:27:30.664: E/AndroidRuntime(13175):    at java.lang.Thread.run(Thread.java:841)
> `
> Please help me out in tracking what exactly is going wrong.

**Comment by alipov** [comment] 2016-04-06 10:57
Strange. 
Try to set the following properties in your Application#onCreate method:

```
System.setProperty("android.javax.xml.stream.XMLInputFactory", "com.sun.xml.stream.ZephyrParserFactory");
System.setProperty("android.javax.xml.stream.XMLOutputFactory", "com.sun.xml.stream.ZephyrWriterFactory");
System.setProperty("android.javax.xml.stream.XMLEventFactory", "com.sun.xml.stream.events.ZephyrEventFactory");
```

Let me know if you're receiving the same error.

**Comment by aqibmapari** [comment] 2016-04-06 12:35
Thanks a lot. It just seems to have gone past that point now. was scratching my head whole day long behind this.

Now getting a new error as below. I suppose this is problem with connection to the host or URL that I have specified. will check that.

> 04-06 18:00:57.488: W/System.err(17431): microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. The request failed. recvfrom failed: ECONNRESET (Connection reset by peer)

Can you please let me know if I am on the right path.

Thanks again.

**Comment by alipov** [comment] 2016-04-06 14:50
Are you able to dump the TCP traffic (easy if you have rooted device, otherwise use some kind of proxy) to better understand what's happening?

**Comment by aqibmapari** [comment] 2016-04-07 04:50
Thanks a lot I have got it working. 
Thanks a lot for your valuable inputs.
Now trying to figure out a way to get html format working properly.
Currently message is going as plain text.

**Comment by aqibmapari** [comment] 2016-05-24 07:26
HI @alipov this workaround does not work on all devices.

One of my user is experiencing this issue with samsung galaxy tab s2 running Android OS 5.0.2.
It is working for other users.
Please help me out if I can do anything to work this around.

**Comment by aqibmapari** [comment] 2016-05-30 09:18
Getting the below error on this particular device I mentioned tab S2

`05-30 11:20:37.041: E/AndroidRuntime(14201): FATAL EXCEPTION: pool-1-thread-1
05-30 11:20:37.041: E/AndroidRuntime(14201): Process: com.intellect.bsalesapp, PID: 14201
05-30 11:20:37.041: E/AndroidRuntime(14201): android.javax.xml.stream.FactoryConfigurationError: Provider com.sun.xml.stream.ZephyrWriterFactory not found
05-30 11:20:37.041: E/AndroidRuntime(14201):    at android.javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at android.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:120)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at android.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at android.javax.xml.stream.XMLOutputFactory.newInstance(XMLOutputFactory.java:98)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at microsoft.exchange.webservices.data.core.EwsServiceXmlWriter.<init>(EwsServiceXmlWriter.java:101)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:690)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:665)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:635)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at microsoft.exchange.webservices.data.core.ExchangeService.internalCreateItems(ExchangeService.java:598)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at microsoft.exchange.webservices.data.core.ExchangeService.createItem(ExchangeService.java:657)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at microsoft.exchange.webservices.data.core.service.item.Item.internalCreate(Item.java:245)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at microsoft.exchange.webservices.data.core.service.item.EmailMessage.internalSend(EmailMessage.java:147)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at microsoft.exchange.webservices.data.core.service.item.EmailMessage.send(EmailMessage.java:258)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at com.phonegap.plugins.Mail.send(Mail.java:104)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at com.phonegap.plugins.SendMail$2.run(SendMail.java:106)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-30 11:20:37.041: E/AndroidRuntime(14201):    at java.lang.Thread.run(Thread.java:818)
`

Its working in most of the devices I have tested but giving error in this particular device mentioned.

**Comment by alipov** [comment] 2016-05-30 14:51
Interesting. My bet is that the class is being rejected by runtime verifier.
Could you please run again and look for verifier errors/warnings?

**Comment by aqibmapari** [comment] 2016-05-31 04:21
Actually I donot have the device with me its users client I got access to it yesterday with great difficulties.
Ill check if I can get access to it.
But If it is the case of rejection of class by runtime verifier then what is the work around for it.
Please suggest.

**Comment by alipov** [comment] 2016-05-31 13:27
Hard to say what the fix will be without seeing the logs.
Unfortunately I don't have such device to test on.

**Comment by aqibmapari** [comment] 2016-05-31 13:33
I'm just getting the log I mentioned in my comment yesterday.
I checked today as well and nothing other than that.
Could it be something related to ART/DALVIK runtime.
Just a guess.

**Comment by alipov** [comment] 2016-05-31 13:43
Do you have access to this device?
I mean, can you debug the app to find inner exception?

**Comment by aqibmapari** [comment] 2016-06-02 05:34
I tried but couldn't get anything more than this.
This is the only exception I'm getting.
I'm afraid I have to move to some other method now.

**Comment by thejaswi28** [comment] 2016-06-22 11:18
@alipov 

I am also getting the same error by adding these 3 lines.

android.javax.xml.stream.FactoryConfigurationError: Provider com.sun.xml.stream.ZephyrWriterFactory not found

**Comment by dabarnard** [comment] 2017-10-24 15:36
@alipov , @thejaswi28 .

I have started experiencing the exact same issue:

> android.javax.xml.stream.FactoryConfigurationError: Provider com.sun.xml.stream.ZephyrWriterFactory not found

after adding:

```
System.setProperty("android.javax.xml.stream.XMLInputFactory", "com.sun.xml.stream.ZephyrParserFactory");
System.setProperty("android.javax.xml.stream.XMLOutputFactory", "com.sun.xml.stream.ZephyrWriterFactory");
System.setProperty("android.javax.xml.stream.XMLEventFactory", "com.sun.xml.stream.events.ZephyrEventFactory");
```

suggested by @alipov 

Have either of you made any progress regarding this issue? One of our users with a Samsung Galaxy Tab 4 running Android 5.0 is experiencing this exact issue.

Any guidance would be greatly appreciated.

**Comment by kjfdebruin** [comment] 2017-11-23 07:44
Any update about this @alipov?

**Comment by alipov** [comment] 2017-12-02 17:01
@dabarnard @kjfdebruin 

It would greatly help if you'll provide instructions (or better yet, github repository with a sample app) for reproducing this error.
I don't possess Samsung Galaxy Tab 4, so I can't reproduce on this device.

If you've already solved this issue, please report back how.

**Comment by dieter-mdp** [comment] 2017-12-06 07:24
@alipov , I have been trying to recreate the bug and will update here if I manage it. Struggling to obtain a Galaxy Tab 4, but hoping to duplicate the bug on other older Samsung devices. So far we only know (for sure) that it happens on the Samsung Galaxy Tab 4 and the Samsung S4.

**Comment by dabarnard** [comment] 2017-12-06 07:26
@alipov  , I have been trying to recreate the bug and will update here if I manage it. Struggling to obtain a Galaxy Tab 4, but hoping to duplicate the bug on other older Samsung devices. So far we only know (for sure) that it happens on the Samsung Galaxy Tab 4 and the Samsung S4.

**Comment by dabarnard** [comment] 2017-12-15 08:06
@alipov,

I managed to get a device where the crash can be recreated.

Interestingly, it doesn't occur on the Samsung S3 or Samsung S4 Mini, but does on the Samsung S4 (running Android 5.0).

It occurs when I fetch events from an Exchange Calendar:

```
FolderId folderId = new FolderId(WellKnownFolderName.Calendar, new Mailbox(emAddr.getAddress()));

FindItemsResults<Appointment> findResults = service.findAppointments(folderId, cView);
```

Here is the Stack Trace once again:

```
android.javax.xml.stream.FactoryConfigurationError: Provider com.sun.xml.stream.ZephyrWriterFactory not found
                                                                        at android.javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72)
                                                                        at android.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:120)
                                                                        at android.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92)
                                                                        at android.javax.xml.stream.XMLOutputFactory.newInstance(XMLOutputFactory.java:98)
                                                                        at microsoft.exchange.webservices.data.core.EwsServiceXmlWriter.<init>(EwsServiceXmlWriter.java:101)
                                                                        at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:690)
                                                                        at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:665)
                                                                        at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:635)
                                                                        at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
                                                                        at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
                                                                        at microsoft.exchange.webservices.data.core.ExchangeService.findItems(ExchangeService.java:985)
                                                                        at microsoft.exchange.webservices.data.core.ExchangeService.findAppointments(ExchangeService.java:1265)
```

After comparing the program execution with a device where no error occurs, it seems like it occurs here:

```
private static ClassLoader findClassLoader() throws FactoryConfigurationError {
        ClassLoader classLoader;
        try {
            Class clazz = Class.forName((class$javax$xml$stream$FactoryFinder == null?(class$javax$xml$stream$FactoryFinder = class$("android.javax.xml.stream.FactoryFinder")):class$javax$xml$stream$FactoryFinder).getName() + "$ClassLoaderFinderConcrete");
            FactoryFinder.ClassLoaderFinder clf = (FactoryFinder.ClassLoaderFinder)clazz.newInstance();
            classLoader = clf.getContextClassLoader();
        } catch (LinkageError var4) {
            classLoader = (class$javax$xml$stream$FactoryFinder == null?(class$javax$xml$stream$FactoryFinder = class$("android.javax.xml.stream.FactoryFinder")):class$javax$xml$stream$FactoryFinder).getClassLoader();
        } catch (ClassNotFoundException var5) {
            classLoader = (class$javax$xml$stream$FactoryFinder == null?(class$javax$xml$stream$FactoryFinder = class$("android.javax.xml.stream.FactoryFinder")):class$javax$xml$stream$FactoryFinder).getClassLoader();
        } catch (Exception var6) {
            throw new FactoryConfigurationError(var6.toString(), var6);
        }

        return classLoader;
    }
```

On devices where the crash occurs the classLoader variable is as follows:

```
dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/WebViewGoogle/WebViewGoogle.apk"],nativeLibraryDirectories=[/system/app/WebViewGoogle/lib/arm, /vendor/lib, /system/lib]]]
```

instead of (on a device with no crash):
```
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myapp.packagename-2/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp.packagename-2/lib/x86, /data/app/com.myapp.packagename-2/base.apk!/lib/x86, /vendor/lib, /system/lib]]]
```
And this then causes the Provider com.sun.xml.stream.ZephyrWriterFactory not found exception to be thrown in FactoryFinder.java

I have no idea where the "/system/app/WebViewGoogle/WebViewGoogle.apk" part comes from, but this is what I think is causing the crash.

That's all I have figured out for now. Not sure why this happens and why it only occurs on Samsung. Do you perhaps have some idea why this would happen? My first thoughts are that it is multidex related?

If you have any suggestions or need me to test anything else - just let me know. I will continue investigating this side, but would appreciate any help/guidance.

**Comment by alipov** [comment] 2017-12-17 18:02
@dabarnard 
Thanks for the detailed description. I'll look into this in a few days.

**Comment by alipov** [comment] 2017-12-19 12:53
@dabarnard 
So I've looked at the stack trace from your last message, and it seems that class loader for some reason rejects the **com.sun.xml.stream.ZephyrWriterFactory** class.
I've tried to test this issue using the following code:
```
System.setProperty("android.javax.xml.stream.XMLInputFactory", "com.sun.xml.stream.ZephyrParserFactory");
System.setProperty("android.javax.xml.stream.XMLOutputFactory", "com.sun.xml.stream.ZephyrWriterFactory");
System.setProperty("android.javax.xml.stream.XMLEventFactory", "com.sun.xml.stream.events.ZephyrEventFactory");

// .. and then..

ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
String className = System.getProperty("android.javax.xml.stream.XMLOutputFactory");
try {
    Class spiClass;
    if (classLoader == null) {
        spiClass = Class.forName(className);
    } else {
        spiClass = classLoader.loadClass(className);
    }
    Object o = spiClass.newInstance();
    Log.d("TEST", "Success");
} catch (ClassNotFoundException x) {
    Log.e("TEST", "ClassNotFoundException", x);
    throw new RuntimeException(x);
} catch (Exception x) {
    Log.e("TEST", "Exception", x);
    throw new RuntimeException(x);
}
```

I've tested this code on the below Samsung devices:
- Samsung S5 (SM-G900F) with Android 6.0.1 (API 23)
- Samsung Note 4 (SM-N910F) with Android 6.0.1 (API 23)
- Samsung Note 2 (GT-N7100) with Android 4.1.2 (API 16)
- Samsung S6 (SM-G925F) with Android 7.0 (API 24)
- Samsung S4 Google Play Edition (GT-I9505G) with Android 5.1 (API 22)

Unfortunately, the class was loaded successfully on all of them. It seems that the error reproduces on a very specific Samsung S4/5.0 configuration.

Could you please run the following code on an S4 device (as part of the application that includes ews-android-api library), just to verify that I've performed the test correctly?

**Comment by dabarnard** [comment] 2017-12-20 09:51
@alipov ,

I just ran your code segment and the following stack trace shows the error:

```
E/TEST: ClassNotFoundException
                              java.lang.ClassNotFoundException: Didn't find class "com.sun.xml.stream.ZephyrWriterFactory" on path: DexPathList[[zip file "/data/app/com.google.android.webview-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.webview-1/lib/arm, /vendor/lib, /system/lib]]
                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                  at com.myapp.package.GetExchangeEvents.onHandleIntent(GetExchangeEvents.java:97)
                                  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                  at android.os.Looper.loop(Looper.java:145)
                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                              	Suppressed: java.lang.ClassNotFoundException: com.sun.xml.stream.ZephyrWriterFactory
                                  at java.lang.Class.classForName(Native Method)
                                  at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                  at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                  		... 6 more
                               Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```
I appreciate the help and your effort. I will continue this side to figure out what is going wrong. Like you said it must be something very specific to the configuration on some devices.

**Comment by alipov** [comment] 2017-12-26 16:56
@dabarnard 

I was able to find a Samsung S4 device (GT-I9505) with Android 5.0.1 - I believe the exact same model (with the same OS) as you're using.

I've compiled a sample application that contains a code snippet from my last message. Unfortunately, the error doesn't reproduce on it.

Can you test my sample application on your device (you can install the [apk](https://github.com/alipov/ews-android-api-issue5/blob/master/dist/app-debug.apk) directly or compile [the project](https://github.com/alipov/ews-android-api-issue5) by yourself)?

**Comment by dabarnard** [comment] 2018-01-05 14:47
@alipov, 

I ran your app on the device and it runs without issue.

This means that it must be a bug very specific to the app I am using your library in and have now figured out the cause:

What I did was to start removing other libraries/code to see if the problem was caused somewhere else and only crashed in your library.  This seems to be the case.

When I removed [this](https://github.com/sephiroth74/android-target-tooltip) library from my app it no longer crashed.

The library in question was used just before I fetched events for a specific calendar using your ews-android-api library - so in some way they must be influencing each-other. I am unsure how though.

But it looks like the issue is not directly related to your library.

**I created a fork and updated your demo app and submitted a PR to your [project](https://github.com/alipov/ews-android-api-issue5/pull/1#issue-286308578) for you to check out if you want to recreate the crash on your side?**

For now, I just removed the other library and everything is working fine.

I am sorry that you had to go through all the effort to help me, and then for it to be related to something not specific to your library alone. But I appreciate your feedback and thank you for the great library and help. Hopefully it wasn't a complete waste of time from your side.

Please let me know if you need anything else from me in order to close the issue.

**Comment by alipov** [comment] 2018-01-08 06:59
@dabarnard 
I was able to reproduce the crash (thanks for PR!). I will investigate it and report back my findings shortly.

**Comment by alipov** [comment] 2018-01-26 12:45
I've fixed the issue with a workaround.

`ews-java-api` implicitly invokes various XML factories. `jsr173` library (which hosts the XML factories) retrieves ClassLoader by calling `Thread.getCurrentThread().getContextClassLoader()`. Some Samsung devices (including the ones that mentioned in this thread) may mistakenly override it:

> dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/WebViewGoogle/WebViewGoogle.apk"],nativeLibraryDirectories=[/system/app/WebViewGoogle/lib/arm, /vendor/lib, /system/lib]]]

Sample code where this error reproduces can be found [here](https://github.com/alipov/ews-android-api-issue5). I'm assuming that the trigger for that (context class loader override) is WebView library load (which since Lollipop is being distributed in a separate APK).

The implemented workaround does few things:
1. Modifying `ews-java-api`'s XML factory method calls by explicitly providing ClassLoader instance.
2. Editing XML factories' fallback class names to Zephyr, thus eliminating the need to register Zephyr classes prior to using the API.
3. While implementing [1], I've found that `jsr173 (v.1.0)`'s `XMLOutputFactory#newInstance(String, ClassLoader)` has a bug - the return type is XMLInputFactory instead of XMLOutputFactory. So I had to provide alternative implementation that contain correct signature.

Anyone having this issue should delete the modified `ews-java-api` source files (located at ews-`project-root/ews-android-api/src/main/java/microsoft`) from the project and run:

> ./gradlew clean copySources ews-android-api:build

Thanks a lot to @dabarnard for providing an exact reproducible scenario!

**Closed as completed** 2018-01-26 12:46 UTC

**Comment by arunsankar8** [comment] 2020-04-23 08:40
Hi @alipov I have been using ews-android-api.jar for implementing the microsoft ews. 
EWS was working fine without an exceptions. 

I had to add the below lines of code to solve the Javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException in the android application.

 try {
            ProviderInstaller.installIfNeeded(getApplicationContext());
            SSLContext sslContext;
            sslContext = SSLContext.getInstance("TLSv1.1");
            sslContext.init(null, null, null);
            sslContext.createSSLEngine();
        } catch (GooglePlayServicesRepairableException | GooglePlayServicesNotAvailableException
                | NoSuchAlgorithmException | KeyManagementException e) {
            e.printStackTrace();
        }

After adding the code, the SSL issue was solved and the API were working fine but the ews keeps crashing giving the below log. 

 Caused by: android.javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.XMLOutputFactoryBase not found
        at android.javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72)
        at android.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:176)
        at android.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92)
        at android.javax.xml.stream.XMLOutputFactory.newInstance(XMLOutputFactory.java:98)
        at microsoft.exchange.webservices.data.core.EwsServiceXmlWriter.<init>(EwsServiceXmlWriter.java:101)
        at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpWebRequest(ServiceRequestBase.java:692)
        at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.buildEwsHttpPoolingWebRequest(ServiceRequestBase.java:682)
        at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:639)
        at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
        at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
        at microsoft.exchange.webservices.data.core.ExchangeService.bindToFolder(ExchangeService.java:505)
        at microsoft.exchange.webservices.data.core.ExchangeService.bindToFolder(ExchangeService.java:523)
        at microsoft.exchange.webservices.data.core.service.folder.CalendarFolder.bind(CalendarFolder.java:60)
        at microsoft.exchange.webservices.data.core.service.folder.CalendarFolder.bind(CalendarFolder.java:75)
        at com.billinar.bookit.helpers.exchange.ExchangeHelper.login(ExchangeHelper.java:183)



Can you please provide the exact steps to resolve the issue.

**Comment by alipov** [comment] 2020-04-24 16:04
@arunsankar8  
Thanks for reporting that.  
It seems that you're using outdated code: `EwsServiceXmlWriter`'s constructor (EwsServiceXmlWriter.java:101) is invoking `XMLOutputFactory.newInstance` (XMLOutputFactory.java:98), instead of `FixedXMLOutputFactory.newInstance`.  

If you still think there's a problem worth looking at, please open a separate issue.

**Comment by arunsankar8** [comment] 2020-04-29 20:17
Thanks @alipov
